defaults:
  project_root: "/data/GNSS/hector-projects/"
  hector_home: "/home/gnss/HECTOR_TEMP/"
paths:
  project_root: "."
  ori_files_dir: "ori_files"
  raw_files_dir: "raw_files"
  obs_files_dir: "obs_files"
  pre_files_dir: "pre_files"
  mom_files_dir: "mom_files"
  sea_files_dir: "sea_files"
  fil_files_dir: "fil_files"
files:
  station_timeseries: ""
  offsets_catalog: ""
  postseismic_catalog: ""
notes:
  description: ""
